//

// AUTH

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_USERNAME = "UPDATE_USERNAME";

// CLIENTS

export const SELECT_CLIENT = "SELECT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const REFRESH_CLIENT_LIST = "REFRESH_CLIENT_LIST";

export const SELECT_DASHBOARDS_SECTION = "SELECT_DASHBOARDS_SECTION";
export const REFRESH_SUBSCRIPTIONS_LIST = "REFRESH_SUBSCRIPTIONS_LIST";

export const SELECT_USERS_SECTION = "SELECT_USERS_SECTION";
export const REFRESH_USERS_LIST = "REFRESH_USERS_LIST";

// USER

export const REFRESH_USER_LIST = "REFRESH_USER_LIST";
